name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "59 23 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        days-before-stale: 20
        days-before-close: 1
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been hanging around a bit too long, if needed please update or comment.'
        stale-pr-message: 'This PR has been hanging around a bit too long, please update/rebase or comment as needed.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
